var tables = {
  TRANS: {
    columns: {
      'PAYMENT_ID': '',
      'CREATED_DATE': '20 Dec 2016 20.00.00.000',
      'LAST_UPDATE': '20 Dec 2016 20.00.00.000',
      'APP_ID': '',
      'APP_NAME': '',
      'REQUEST_ID': '122333444455555',
      'PAYER_ID': 'Robot',
      'REF1': 'REF1',
      'REF2': 'REF2',
      'REF3': 'REF3',
      'AMOUNT': '',
      'CURRENCY': 'THB',
      'RESULT_CODE': '0',
      'RESULT_DESC': 'SUCCESS',
      'USER_MESSAGE': 'SUCCESS',
      'PROCESSOR': '',
      'INTENT': 'test',
      'PAYMENT_TYPE': 'embed',
      'RETURN_URL': 'http://localhost.com/return',
      'CANCEL_URL': 'http://localhost.com/cancel',
      'TRANS_STATE': '',
      'ACK_STATE': 'SUCCESS',
      'AUTHORIZE_STATE': 'SUCCESS',
      'AUTHORIZED_DATE': '20 Dec 2016 20.00.00.000',
      'PAYMENT_DATE': '',
      'RECONCILE_STATE': 'INIT',
      'RECONCILE_DATE': '20 Dec 2016 20.00.00.000',
      'SOF_TYPE': '',
      'SOF_GW_TRANS_ID': '122333444455555666666',
      'SOF_REF1': '999999xxxxxx9999',
      'SOF_REF2': '122333',
      'SOF_REF3': 'TEST',
      'CARD_TYPE': 'CARD_TYPE',
      'TERM': 0,
      'INTEREST_TO': 'INTEREST_TO',
      'INTEREST': 0,
      'MDR': 'MDR',
      'NET_TRANSFER_AMOUNT': 0,
      'MDR_AMOUNT': 0,
      'VAT_AMOUNT': 0,
      'INTEREST_AMOUNT': 0,
      'TRANS_FEE': 0,
      'TAX_RECEIPT_NO': 'TAX_RECEIPT_NO',
      // 'BILLING_DATE': null,
      'BILLING_REF': 'BILLING_REF'
    }
  }
}